CIS collector for OpenStack
seecloud/cis-collector-openstack pull request #3
Opened 2016-11-03 15:50 UTC by corest

CIS collector for openstack includes:
  - collectors for keystone, nova, glance, cinder and neutron
  - resource generation, casting and validation
  - testing backing application

2016-11-14 06:42 UTC, boris-42 commented
@corest can you please update patches so they will pass the gates

2016-11-14 23:17 UTC, boris-42 commented
@corest please use push force to fix the history, I don't want to have non working commits in history.

2016-11-17 07:55 UTC, boris-42 requested changes

2016-11-17 07:55 UTC, boris-42 commented on oscollector/service_collector.py
> +from settings import SERVICE_INVALID_STATE
Please fix imports in all files. 

your imports should look like next: 

section_of_std_lib
<blank_line>
section_of_external_libs
<blank_line>
section_of_your_modules

Import only modules, do not import anything from modules, as well do not use * and try to avoid as

2016-11-17 11:32 UTC, corest commented
Updated with reodered imports

2016-11-18 17:16 UTC, closed without merging